### ISSUE TITLE
Parse error: syntax error, unexpected '.', expecting ',' or ';' in /Applications/AMPPS/www/swifost.dev/libraries/Swifost/Swifost.php on line 57

### ISSUE THREAD

**Issue by visualcookie** [jofpin/swifost#2]
Hi,

I wanted to check out your system, but I'm getting an error.

PHP: 5.5

**Comment by jofpin** [comment]
How strange , beareth a solution of line 57. Thanks!

**Comment by visualcookie** [comment]
Well, I just commented that line out. Worked for testing.

**Comment by jofpin** [comment]
I have already answered your error, check friend .
