### ISSUE TITLE
install.php <script> tags

### ISSUE THREAD

**Issue by crazy4groovy** [jofpin/swifost#4]
Just a tip, if you put your `<script>`s at the end of the page, you don't need to wait for document.ready event to do your JS code things.

https://github.com/jofpin/swifost/blob/master/install.php#L138

**Comment by jofpin** [comment]
Understanding friend and I fix , but have a problem in the installation ?

**Comment by crazy4groovy** [comment]
No problem! (haven't tried yet) Just looking :)
