### ISSUE TITLE
installation Warning: explode() -Warning: Cannot modify header information

### ISSUE THREAD

**Issue by ortegoncarlos** [jofpin/swifost#6]
Hi guys,

I've been trying to install the framework "as a test", in a shared hosting, it seems that all permissions are right, httacces and php version are ok but when i run the install throw me this errors, and the installation starts over again.

any suggestions?

Warning: explode() expects parameter 2 to be string, array given in /home/pulsakr2/public_html/swfost/swifost-master/libraries/Swifost/Swifost.php on line 270

Warning: Invalid argument supplied for foreach() in /home/pulsakr2/public_html/swfost/swifost-master/libraries/Swifost/Swifost.php on line 271

Warning: Cannot modify header information - headers already sent by (output started at /home/pulsakr2/public_html/swfost/swifost-master/libraries/Swifost/Swifost.php:270) in /home/pulsakr2/public_html/swfost/swifost-master/libraries/Swifost/Swifost.php on line 252

Warning: Cannot modify header information - headers already sent by (output started at /home/pulsakr2/public_html/swfost/swifost-master/libraries/Swifost/Swifost.php:270) in /home/pulsakr2/public_html/swfost/swifost-master/libraries/Swifost/Swifost.php on line 252

**Comment by jofpin** [comment]
Friend everything works fine, you can see here : http://swifost-jofpin.c9.io/

Code: https://ide.c9.io/jofpin/swifost

It should be your version of php!
